#!/usr/bin/env python

import os
from mreschke.wiki.services import bootstrap

# Play
# from pydantic import BaseSettings
# class Settings(BaseSettings):
#     PIPENV_SKIP_LOCK: bool
#     TEST: str = 'hi'
# settings = Settings()
# print(settings)


# Bootstrap the Uvicore application
app = bootstrap.application(is_console=True)

# Initialize CLI
if __name__ == '__main__':
    app.cli()
