#!/usr/bin/env python

import os
import uvicore
from mreschke.wiki.services import bootstrap
from uvicore.support.dumper import dump, dd

# Bootstrap the Uvicore application
app = bootstrap.application(is_console=True)

# Initialize CLI
if __name__ == '__main__':
    # Run the main click group by executing the actual method in the Ioc
    uvicore.ioc.make('Console')()
